### ISSUE TITLE
provisioning volkovlabs-grapi-datasource plugin

### ISSUE THREAD

**Issue by Mhatagada** [VolkovLabs/volkovlabs-grapi-datasource#41]
Hi,

I want to provision volkovlabs-grapi-datasource plugin in grafana using the yaml file in grafana/provisioning/plugins

can you say me what I have to write in the yaml ?

I tried :
```
apiVersion: 1

apps:
  - type: volkovlabs-grapi-datasource
    disabled: false
```
but doesn't work and grafana don't start
and I don't want to use grafana-cli to install the plugin

thanks for your help
